import {useEffect,useState} from "react";
import {Button} from "./components/ui/button";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";
import {Input} from "./components/ui/input";
import {Label} from "./components/ui/label";
import {api,base} from "./api";
import "./theme.css";
type Config={enabled:boolean;timezone:string;start_minutes:number;due_minutes:number;retention_days:number;progress_status:string;done_status:string;archive_status:string};
export default function SettingsTab({projectId}:{projectId:string}){const path=base+projectId;const [cfg,setCfg]=useState<Config>({enabled:false,timezone:"Asia/Shanghai",start_minutes:10,due_minutes:10,retention_days:90,progress_status:"",done_status:"",archive_status:""});const [rev,setRev]=useState(0);const [states,setStates]=useState<{id:string;name:string}[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [connection,setConnection]=useState("");const [device,setDevice]=useState("Obsidian");const [pairing,setPairing]=useState<{id:string;token:string}|null>(null);const [revoke,setRevoke]=useState("");const [records,setRecords]=useState<{id:string;title:string;kind:string;submitted_at:string;status:string}[]>([]);
const load=async()=>{const r=await api<{config:Config;revision:number;last_error?:string}>(path+"/settings");setCfg(r.config);setRev(r.revision);if(r.last_error)setMessage(r.last_error);setStates((await api<{items:{id:string;name:string}[]}>(`/api/v1/projects/${projectId}/task-statuses`)).items);setRecords((await api<{items:typeof records}>(path+"/records")).items)};useEffect(()=>{load().catch(e=>setMessage(e.message))},[projectId]);const act=async(fn:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await fn()}catch(e){setMessage(String(e))}finally{setBusy(false)}};const number=(key:"start_minutes"|"due_minutes"|"retention_days",text:string)=>setCfg({...cfg,[key]:Number(text)});
return <div className="checkin-ui grid gap-5 p-4"><Card><CardHeader><CardTitle>任务拍照打卡</CardTitle><CardDescription>开始、结束分别在提前窗口内有效，到点关闭。两张卡可独立提交。</CardDescription></CardHeader><CardContent className="grid gap-4"><Label><input type="checkbox" checked={cfg.enabled} onChange={e=>setCfg({...cfg,enabled:e.target.checked})}/> 启用本项目打卡</Label><Label>时区<Input value={cfg.timezone} onChange={e=>setCfg({...cfg,timezone:e.target.value})}/></Label><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{([['start_minutes','开始提前（分钟）'],['due_minutes','结束提前（分钟）'],['retention_days','照片保留（天）']] as const).map(([k,label])=><Label key={k}>{label}<Input type="number" min="1" value={cfg[k]} onChange={e=>number(k,e.target.value)}/></Label>)}</div>{([['progress_status','开始打卡后状态'],['done_status','结束打卡后状态'],['archive_status','手动归档状态']] as const).map(([k,label])=><Label key={k}>{label}<select value={cfg[k]} onChange={e=>setCfg({...cfg,[k]:e.target.value})}><option value="">请选择项目实际状态</option>{states.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Label>)}<Button disabled={busy} onClick={()=>act(async()=>{await api(path+"/settings",{config:cfg,revision:rev},"PUT");await load();setMessage("设置已保存")})}>保存设置</Button></CardContent></Card><Card><CardHeader><CardTitle>Obsidian 设备配对</CardTitle><CardDescription>每个设备单独授权；令牌只显示一次。来源连接 UUID 从 TaskNotes 接入插件复制。</CardDescription></CardHeader><CardContent className="grid gap-3"><Label>来源连接 UUID<Input value={connection} onChange={e=>setConnection(e.target.value)}/></Label><Label>设备名称<Input value={device} onChange={e=>setDevice(e.target.value)}/></Label><Button disabled={busy} onClick={()=>act(async()=>setPairing(await api(path+"/pairing",{name:device,connection_id:connection})))}>生成配对凭据</Button>{pairing&&<div className="grid gap-2"><Label>设备 ID<Input readOnly value={pairing.id}/></Label><Label>配对令牌<Input readOnly type="password" value={pairing.token}/></Label><Button variant="outline" onClick={()=>navigator.clipboard.writeText(pairing.token).then(()=>setMessage("已复制配对令牌"))}>复制令牌</Button></div>}<Label>撤销设备 ID<Input value={revoke} onChange={e=>setRevoke(e.target.value)}/></Label><Button variant="outline" disabled={busy||!revoke} onClick={()=>act(async()=>{await api(path+"/pairing/"+encodeURIComponent(revoke),undefined,"DELETE");setMessage("设备凭据已撤销")})}>撤销设备</Button></CardContent></Card><Card><CardHeader><CardTitle>最近打卡</CardTitle></CardHeader><CardContent className="grid gap-3">{records.length?records.map(r=><div key={r.id} className="rounded-lg border p-3"><p>{r.title} · {r.kind==="start"?"开始":"结束"}</p><p className="text-sm text-muted-foreground">{new Date(r.submitted_at).toLocaleString()} · {r.status==="synced"?"已同步":"状态同步中"}</p></div>):<p className="text-muted-foreground">暂无打卡记录</p>}</CardContent></Card>{message&&<p role="status">{message}</p>}</div>}
