import {useEffect,useState} from "react";
import {Button} from "./components/ui/button";
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "./components/ui/select";
import {api} from "./api";

type Device={name:string;state:string;attempts:number;error_code:string;media_verified:boolean;record_written:boolean;status_verified:boolean};
type Binding={path:string;note_created:string;title:string};
type Row={record_id:string;connection_id:string;title:string;kind:string;submitted_at:string;policy:string;revision:number;paca_status:string;devices:Device[]};
const stages:Record<string,string>={pending:"等待同步",retry_wait:"等待重试",needs_action:"需要处理",confirmed:"回写完成",ignored:"已忽略",archived_deleted:"任务已删除，已归档"};
const errors:Record<string,string>={transfer_unavailable:"照片传输中断",unavailable:"服务暂不可用",photo:"照片校验未完成",missing:"任务笔记需要关联",source_missing:"任务来源需要关联",block:"打卡区块有修改",status:"任务状态有冲突",token:"授权已失效"};
export default function SyncDeliveries({path}:{path:string}){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [bindings,setBindings]=useState<Record<string,Binding[]>>({}),[target,setTarget]=useState<Record<string,string>>({});
 const associate=async(row:Row)=>{if(!bindings[row.connection_id]){try{const project=path.split("/projects/")[1];const reply=await api<{items:Binding[]}>("/plugins/com.selfcommand.tasknotes-webhook/projects/"+project+"/connections/"+row.connection_id+"/note-bindings");setBindings(old=>({...old,[row.connection_id]:reply.items}));setMessage(reply.items.length?"请选择对应任务笔记。":"没有可关联的笔记，请在 Obsidian 中选择。")}catch{setMessage("暂时无法加载笔记，请在 Obsidian 中重新关联。")}return;}const binding=bindings[row.connection_id].find(b=>b.path===target[row.record_id]);if(!binding){setMessage("请选择对应的任务笔记。");return;}setBusy(true);try{await api(path+"/sync-delivery-actions",{connection_id:row.connection_id,record_id:row.record_id,op_id:crypto.randomUUID(),action:"associate",base_revision:row.revision,path:binding.path,note_created:binding.note_created});setMessage("关联请求已提交，只同步打卡记录和照片。");await load()}catch{setMessage("暂时无法保存关联，请刷新后重试。")}finally{setBusy(false)}};
 const load=async()=>setRows((await api<{items:Row[]}>(path+"/sync-deliveries")).items);
 useEffect(()=>{void load().catch(()=>setMessage("暂时无法加载同步记录，请稍后重试。"));const timer=window.setInterval(()=>void load().catch(()=>{}),5000);return()=>window.clearInterval(timer)},[path]);
 const act=async(action:string,items:Row[])=>{if(action==="ignore"&&!window.confirm(`忽略所选 ${items.length} 条同步记录？同一笔记库的设备都会停止重试，打卡记录和照片仍会保留。`))return;setBusy(true);setMessage("");let submitted=0;try{for(const row of items){await api(path+"/sync-delivery-actions",{connection_id:row.connection_id,record_id:row.record_id,op_id:crypto.randomUUID(),action,base_revision:row.revision});submitted++;}setSelected(new Set());setMessage("处理请求已提交，请刷新查看结果。");await load()}catch{setMessage(`已提交 ${submitted} 条；其余记录暂未处理，请刷新后重试。`)}finally{setBusy(false)}};
 return <Card><CardHeader><CardTitle>Obsidian 同步处理</CardTitle><CardDescription>查看照片和记录回写进度，处理失败记录。</CardDescription></CardHeader><CardContent className="grid gap-3"><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>void load().catch(()=>setMessage("暂时无法刷新，请稍后重试。"))}>刷新记录</Button><Button variant="outline" disabled={busy||!selected.size} onClick={()=>void act("ignore",rows.filter(r=>selected.has(r.record_id)))}>清理所选故障项</Button></div>{rows.length?rows.map(row=><div className="grid gap-2 rounded-lg border p-3" key={row.record_id}><label className="flex items-center gap-2"><input type="checkbox" checked={selected.has(row.record_id)} disabled={row.policy!=="active"} onChange={e=>setSelected(old=>{const next=new Set(old);if(e.target.checked)next.add(row.record_id);else next.delete(row.record_id);return next})}/><span>{row.title} · {row.kind==="start"?"开始打卡":"结束打卡"}</span></label><p className="text-sm text-muted-foreground">{new Date(row.submitted_at).toLocaleString()} · {row.paca_status==="synced"?"Paca 状态已更新":"Paca 状态更新中"}</p>{row.policy!=="active"?<p className="text-sm">{stages[row.policy]}</p>:row.devices.length?row.devices.map((d,i)=><div key={i} className="text-sm"><p>{d.name}：{stages[d.state]??"等待同步"}{d.error_code?" · "+(errors[d.error_code]??"需要处理同步记录"):""}</p><p className="text-muted-foreground">照片：{d.media_verified?"已保存":"待保存"} · 记录：{d.record_written?"已写入":"待写入"}</p></div>):<p className="text-sm text-muted-foreground">等待设备同步</p>}<div className="flex flex-wrap gap-2">{row.policy==="active"?<><Button size="sm" variant="outline" disabled={busy} onClick={()=>void act("retry",[row])}>重试同步</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>void act("ignore",[row])}>忽略此同步项</Button></>:<Button size="sm" variant="outline" disabled={busy} onClick={()=>void act("restore",[row])}>恢复同步</Button>}<Button size="sm" variant="outline" disabled={busy} onClick={()=>void associate(row)}>重新关联笔记</Button></div>{bindings[row.connection_id]?.length>0&&<Select value={target[row.record_id]??""} onValueChange={value=>setTarget(old=>({...old,[row.record_id]:value}))}><SelectTrigger><SelectValue placeholder="选择对应任务笔记"/></SelectTrigger><SelectContent>{bindings[row.connection_id].map(note=><SelectItem key={note.path} value={note.path}>{note.title} · {note.path}</SelectItem>)}</SelectContent></Select>}</div>):<p className="text-sm text-muted-foreground">暂无同步记录</p>}{message&&<p className="text-sm" role="status">{message}</p>}</CardContent></Card>;
}
