import {useEffect,useRef,useState} from "react";import {createRoot} from "react-dom/client";import {Card,CardHeader,CardTitle,CardDescription,CardContent} from "./components/ui/card";import {Button} from "./components/ui/button";import {Badge} from "./components/ui/badge";import {Progress} from "./components/ui/progress";import {Textarea} from "./components/ui/textarea";import {Label} from "./components/ui/label";import {api} from "./api";import "./theme.css";
type View={instance_id:string;revision:number;title:string;kind:string;server_time:string;opens_at:string;closes_at:string;state:string;record?:{id:string;submitted_at:string;status:string;note:string}|null};const root="/checkin-api/v1/";
function App(){const [view,setView]=useState<View|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState("");const [note,setNote]=useState("");const [progress,setProgress]=useState(0);const [now,setNow]=useState(Date.now());const offset=useRef(0);const media=useRef<{media_id:string}|null>(null);const xhr=useRef<XMLHttpRequest|null>(null);const op=useRef("");
async function load(){const data=await api<View>(root+"session");offset.current=new Date(data.server_time).getTime()-Date.now();setNow(Date.now()+offset.current);setView(data)}
useEffect(()=>{let active=true;(async()=>{try{const token=new URLSearchParams(location.hash.slice(1)).get("token");history.replaceState(null,"",location.pathname);if(token)await api(root+"exchange",{token});if(active)await load()}catch(e){if(active)setError(String(e))}finally{if(active)setLoading(false)}})();const timer=setInterval(()=>{setNow(Date.now()+offset.current)},1000);const refresh=setInterval(()=>{load().catch(e=>setError(String(e)))},15000);return()=>{active=false;clearInterval(timer);clearInterval(refresh);xhr.current?.abort()}},[]);
useEffect(()=>{if(!file){setPreview("");return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
function select(value:File|undefined){if(!value)return;if(value.size>10*1024*1024){setError("照片不能超过 10 MiB");return}if(!["image/jpeg","image/png","image/webp"].includes(value.type)){setError("请选择 JPEG、PNG 或 WebP 格式照片");return}setError("");media.current=null;op.current="";setFile(value)}
async function upload(f:File){return new Promise<{media_id:string}>((resolve,reject)=>{const x=new XMLHttpRequest();xhr.current=x;x.open("POST",root+"photos");x.withCredentials=true;x.setRequestHeader("Content-Type",f.type);x.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};x.onload=()=>{try{const data=JSON.parse(x.responseText);if(x.status>=200&&x.status<300)resolve(data);else reject(new Error(data.error??"照片上传失败"))}catch{reject(new Error("上传返回无效，请重试"))}};x.onerror=()=>reject(new Error("网络中断，照片上传失败"));x.onabort=()=>reject(new Error("上传已取消"));x.send(f)})}
async function submit(){if(!file||!view)return;setBusy(true);setError("");try{if(!media.current)media.current=await upload(file);const key="checkin-op:"+view.instance_id+":"+view.kind;if(!op.current){op.current=sessionStorage.getItem(key)??crypto.randomUUID();sessionStorage.setItem(key,op.current)}await api(root+"submit",{media_id:media.current.media_id,op_id:op.current,note,revision:view.revision});await load();sessionStorage.removeItem(key);setFile(null)}catch(e){setError(String(e));await load().catch(()=>{})}finally{setBusy(false)}}
const submitted=!!view?.record;const open=!!view&&now>=new Date(view.opens_at).getTime()&&now<new Date(view.closes_at).getTime();const seconds=view?Math.max(0,Math.ceil((new Date(view.closes_at).getTime()-now)/1000)):0;
return <main className="checkin-ui min-h-dvh bg-background px-4 py-8"><div className="mx-auto grid max-w-lg gap-5"><p className="text-sm text-muted-foreground">{location.hostname} · 任务打卡</p><Card><CardHeader><div className="mb-3"><Badge variant={submitted?"default":"secondary"}>{submitted?"已打卡":loading?"正在读取":open?"窗口开放":"窗口未开放或已截止"}</Badge></div><CardTitle className="text-2xl"><h1>{view?.title??"拍照打卡"}</h1></CardTitle><CardDescription>{view?.kind==="start"?"开始打卡":view?.kind==="due"?"结束打卡":"正在验证提醒入口"}</CardDescription></CardHeader><CardContent className="grid gap-5">{loading?<p>正在加载…</p>:view?<><div className="rounded-lg bg-muted p-4 text-sm"><p>有效期：{new Date(view.opens_at).toLocaleString()} 至 {new Date(view.closes_at).toLocaleString()}</p><p className="mt-1">到点关闭，以服务器最终确认时间为准。</p>{open&&!submitted&&<p className="mt-2 font-medium" aria-live="off">剩余 {Math.floor(seconds/60)} 分 {seconds%60} 秒</p>}</div>{submitted?<div role="status"><p className="font-medium">打卡成功</p><p>{view.record?.status==="synced"?"任务状态已同步":"任务状态同步中，无需重新拍照"}</p><p className="text-sm text-muted-foreground">{view.record?.submitted_at&&new Date(view.record.submitted_at).toLocaleString()}</p></div>:<><div className="grid grid-cols-2 gap-3"><Button variant="outline" asChild><Label>拍照<input aria-label="拍照" className="hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={busy||!open} onChange={e=>select(e.target.files?.[0])}/></Label></Button><Button variant="outline" asChild><Label>从相册选择<input aria-label="从相册选择" className="hidden" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!open} onChange={e=>select(e.target.files?.[0])}/></Label></Button></div>{preview&&<img className="max-h-80 w-full rounded-lg object-contain" src={preview} alt="待提交照片预览"/>}<Label>备注（可选）<Textarea maxLength={4000} value={note} disabled={busy||!open} onChange={e=>setNote(e.target.value)} placeholder="记录这一刻…"/></Label>{busy&&<div><Progress value={progress}/><p className="mt-2 text-sm">{progress<100?`上传中 ${progress}%`:"正在确认打卡…"}</p></div>}<Button size="lg" disabled={!file||busy||!open} onClick={submit}>{busy?"提交中…":"确认打卡"}</Button>{!open&&<p role="status">尚未开始或已截止。上传照片不能延长打卡窗口。</p>}</>}</>:<p>入口已过期、取消或不可用。</p>}{error&&<p className="text-sm text-destructive" role="alert">{error}</p>}<Button variant="ghost" disabled={busy} onClick={()=>load().then(()=>setError("")).catch(e=>setError(String(e)))}>刷新状态</Button></CardContent></Card></div></main>}
createRoot(document.getElementById("root")!).render(<App/>);
